/**Authentication actions */
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const FETCH_USER = "FETCH_USER";

/** Visualization actions */
export const SAMPLE_SELECTED = "SAMPLE_SELECTED";
export const ANTIBIOTIC_SELECTED = "ANTIBIOTIC_SELECTED";
export const SHOW_AMR_TABLE = "SHOW_AMR_TABLE";
export const FETCH_PACKED_CIRCLE_DATA = "FETCH_PACKED_CIRCLE_DATA";
export const FETCH_PACKED_CIRCLE_RESTORE_DATA = "FETCH_PACKED_CIRCLE_RESTORE_DATA";

export const DELETE_SAMPLE = "DELETE_SAMPLE";
export const RESTORE_SAMPLE = "RESTORE_SAMPLE";
